[tools]
actionlint = "latest"
crane = "latest"
gitleaks = "8.22"
go = "1.23.1"
golangci-lint = "latest"
hadolint = "latest"
jq = "1"
markdownlint-cli2 = "latest"
shellcheck = "latest"
snyk = "latest"
task = "3"
trivy = "latest"
yamllint = "latest"
