name: Update Badge
#
# Requires 'contents: write' and 'actions: write' permissions for the workflow caller.
#

on:
  repository_dispatch:
    types: [badge-update]

permissions:
  contents: read

jobs:
  badge_file_updater:
    name: Update Badge ${{ github.event.client_payload.label }}
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: Harden the runner
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          policy: default
      - name: Validate inputs
        id: validate
        run: |
          if [[ -z "${{ github.event.client_payload.icon_width }}" ]] || [[ ! "${{ github.event.client_payload.icon_width }}" =~ ^[0-9]+$ ]]; then
            echo "Invalid icon_width" >&2
            exit 1
          fi
          if [[ ! "${{ github.event.client_payload.label }}" =~ ^[a-zA-Z0-9_\ -]+$ ]]; then
            echo "Invalid label format - must contain only alphanumeric characters, spaces, underscores, or hyphens" >&2
            exit 1
          fi
          lowercase_label=$(echo "${{ github.event.client_payload.label }}" | tr '[:upper:]' '[:lower:]' | tr ' ' '-')
          if [[ "${{ github.event.client_payload.path }}" != "${lowercase_label}.svg" ]]; then
            echo "Invalid path value" >&2
            exit 1
          fi
          if [[ ! "${{ github.event.client_payload.label_color }}" =~ ^($VALID_LABEL_COLORS)$ ]] || [[ -z "${{ github.event.client_payload.label_color }}" ]]; then
            echo "Invalid label_color" >&2
            exit 1
          fi
          if [[ ! "${{ github.event.client_payload.status }}" =~ ^[a-zA-Z0-9_\ -]+$ ]]; then
            echo "Invalid status format - must contain only alphanumeric characters, spaces, underscores, or hyphens" >&2
            exit 1
          fi
          if [[ ! "${{ github.event.client_payload.status_color }}" =~ ^($VALID_STATUS_COLORS)$ ]] || [[ -z "${{ github.event.client_payload.status_color }}" ]]; then
            echo "Invalid status_color" >&2
            exit 1
          fi
        env:
          VALID_LABEL_COLORS: '555'
          VALID_STATUS_COLORS: 'red|green|blue|yellow|orange|purple|cyan|magenta|lime|pink|teal|lavender|brown|beige|maroon|mint|olive|coral|navy|grey|gray|black|white|success|important|critical|informational|inactive|lightgrey|gray|lightgray'
      - name: Checkout repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # ratchet:actions/checkout@v4
        with:
          token: ${{ secrets.BOT_TOKEN }}
          fetch-depth: 0
      - name: Prepare badges branch
        run: |
          if git ls-remote --exit-code origin badges; then
            git switch badges
          else
            git switch --orphan badges
            [[ -z "$(git ls-files)" ]] || git rm -rf .
          fi
      - name: Create badge
        uses: emibcn/badge-action@808173dd03e2f30c980d03ee49e181626088eee8 # ratchet:emibcn/badge-action@v2
        # Use https://www.svgviewer.dev/svg-to-data-uri to get a data URI
        with:
          icon: ${{ github.event.client_payload.icon }}
          icon-width: ${{ github.event.client_payload.icon_width }}
          label: ${{ github.event.client_payload.label }}
          label-color: ${{ github.event.client_payload.label_color }}
          status: ${{ github.event.client_payload.status }}
          color: ${{ github.event.client_payload.status_color }}
          path: ${{ github.event.client_payload.path }}
      - name: Push changes
        env:
          BADGE_LABEL: ${{ github.event.client_payload.label }}
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            gpg --import <(echo "${{ secrets.BOT_GPG_PRIVATE_KEY_BASE64 }}" | base64 -d)
            git config user.name "gha-bot"
            git config user.email "gha-bot.noreply.wdx1x@tenet.pm"
            git config user.signingkey "ABD02F54EDDADCB6"
            git config commit.gpgsign true
            git status --porcelain
            git add --all
            safe_label="$(echo "$BADGE_LABEL" | tr -cd '[:alnum:]_-')"
            git commit -m "ci: update ${safe_label} badge [skip ci]"
            git push origin badges --force
          else
            echo "No changes to commit."
          fi
