name: Security Compliance

on:
  workflow_dispatch:
    inputs:
      job:
        description: Job to run
        type: choice
        options:
          - Lint commit messages
          - Secrets Scan
          - Vulnerability Scan
        required: false
        default: Vulnerability Scan
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  lint_commits:
    name: Lint commit messages
    runs-on: ubuntu-latest
    timeout-minutes: 1
    if: |
      github.event.inputs.job == 'Lint commit messages' ||
      (github.event.forced == false &&
      github.actor != 'dependabot[bot]' &&
      !startsWith(github.head_ref, 'release-please'))
    permissions:
      contents: read
      pull-requests: read
    steps:
      - name: Harden the runner
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          policy: default
          egress-policy: audit
      - name: Checkout repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # ratchet:actions/checkout@v4
      - uses: wagoid/commitlint-github-action@b948419dd99f3fd78a6548d48f94e3df7f6bf3ed # ratchet:wagoid/commitlint-github-action@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          configFile: .github/.linters/commitlint.config.mjs

  secrets_scan:
    name: Secrets Scan
    runs-on: ubuntu-latest
    timeout-minutes: 1
    if: |
      github.event.inputs.job == 'Secrets Scan' ||
      (github.actor != 'dependabot[bot]' &&
      !startsWith(github.head_ref, 'release-please'))
    permissions:
      contents: read
      pull-requests: read
    steps:
      - name: Harden the runner
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          policy: default
          egress-policy: audit
      - name: Checkout repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # ratchet:actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Scan
        uses: gitleaks/gitleaks-action@83373cf2f8c4db6e24b41c1a9b086bb9619e9cd3 # ratchet:gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_CONFIG: ${{ github.workspace }}/.security/gitleaks.toml
          GITLEAKS_ENABLE_UPLOAD_ARTIFACT: false # sarif upload, would need 'security-events: write'
          GITLEAKS_ENABLE_SUMMARY: true
          GITLEAKS_VERSION: 8.22.0

  vulnerability_scan:
    name: Vulnerability Scan
    runs-on: ubuntu-latest
    timeout-minutes: 3
    if: |
      github.event.inputs.job == 'Vulnerability Scan' ||
      github.actor != 'dependabot[bot]'
    permissions:
      contents: read
      pull-requests: write
      actions: write
      security-events: write
    steps:
      - name: Harden the runner
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          policy: default
          egress-policy: audit
      - name: Checkout repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # ratchet:actions/checkout@v4
      - name: Detect vulnerabilities
        uses: aquasecurity/trivy-action@6c175e9c4083a92bbca2f9724c8a5e33bc2d97a5 # ratchet:aquasecurity/trivy-action@master
        with:
          scan-type: fs
          github-pat: ${{ secrets.GITHUB_TOKEN }}
          format: github
          trivy-config: .security/trivy.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Detect new vulnerabilities
        if: github.event_name == 'pull_request'
        uses: AikidoSec/github-actions-workflow@47d83dbcf3e6635044c4b31cef590c1e095217cc # ratchet:AikidoSec/github-actions-workflow@v1.0.13
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          secret-key: ${{ secrets.AIKIDO_SECRET_KEY }}
          fail-on-timeout: true
          fail-on-dependency-scan: true
          fail-on-sast-scan: false
          fail-on-iac-scan: false
          minimum-severity: CRITICAL
          timeout-seconds: 180
          post-scan-status-comment: on
          post-sast-review-comments: on
