name: Update OSSF Scorecard

on:
  workflow_dispatch:
    inputs:
      job:
        description: Job to run
        type: choice
        options:
          - Scorecard analysis
        required: false
        default: Scorecard analysis
  # For Branch-Protection check. Only the default branch is supported.
  # https://github.com/ossf/scorecard/blob/main/docs/checks.md#branch-protection
  branch_protection_rule:
  schedule:
    - cron: '15 12 1-7 * 5' # first Friday of each month
  push:
    branches: [main]

permissions: {}

jobs:
  ossf_scorecard_analysis:
    name: Scorecard analysis
    runs-on: ubuntu-latest
    timeout-minutes: 1
    permissions:
      contents: read
      actions: read
      security-events: write
      id-token: write
    steps:
      - name: Run analysis
        uses: ossf/scorecard-action@f49aabe0b5af0936a0987cfb85d86b75731b0186 # ratchet:ossf/scorecard-action@v2.4.1
        with:
          results_file: ossf-scorecard.sarif
          results_format: sarif
          publish_results: true
      - name: Upload artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # ratchet:actions/upload-artifact@v4
        with:
          name: OSSF Scorecard
          path: ossf-scorecard.sarif
          retention-days: 31
      - name: Upload to code-scanning
        uses: github/codeql-action/upload-sarif@5f8171a638ada777af81d42b55959a643bb29017 # ratchet:github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ossf-scorecard.sarif
